CREATE TABLE draftlings (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    content TEXT,
    wordcount TEXT,
    genre TEXT,
    modified TIMESTAMPTZ DEFAULT now() NOT NULL,
    status TEXT
);
